config/routes.rb
TACRM::Application.routes.draw do
  
  get "transactions/new"
  get "transactions/create"
  get "portal/index"
  get "system_updates/index"
  get "users/index"
  get "users/new"
  get "users/create"
  get "users/edit"
  get "users/update"
  get "users/show"
  get "users/destroy"
  resources :profile_versions

  devise_for :users
  scope "/admin" do
    resources :users do
      get :activate, on: :member
    end
  end

  resources :transactions

  
  resources :identifications
  get 'identification/:id/doc_image/download/:version' => 'doc_image#download', as: 'download_doc_image'
  get 'identification/:id/doc_image/new' => 'doc_image#new', as: 'new_doc_image'
  get 'identification/:id/doc_image/view' => 'doc_image#view', as: 'view_doc_image'
  post 'identification/:id/doc_image/upload' => 'doc_image#upload', as: 'upload_doc_image'
  delete 'identification/:id/doc_image/destroy' => 'doc_image#destroy', as: 'delete_doc_image'
  resources :notes

  resources :members

  resources :groups

  resources :accounts

  resources :addresses

  resources :phones

  resources :profiles do
    get  :json, on: :collection
    post :json, on: :collection
    get :datatable, on: :collection
    get :corporate_index, on: :collection
    get :lock, on: :member
    get :unlock, on: :member
    delete :delete, on: :member
    post :restore, on: :member
    get :lock_all, on: :collection
    get :unlock_all, on: :collection
    get :view_deleted, on: :collection
  end
  get 'transaction/new/profile/:profile_id' => 'transactions#new', as: 'profile_new_transaction'
  get 'identifications/passports/expiring' => 'identifications#expiring', as: 'expiring_passports'
  get 'identifications/new/profile/:profile_id' => 'identifications#new', as: 'profile_new_identification'
  get 'profile/:id/panel/:panel_number' => 'profiles#show', as: 'profile_panel'
  get 'versions/profile/:profile_id' => 'profile_versions#index', as: 'versions_profile'
  get 'profile/search' => "profiles#search", as: "profile_search"
  get 'profile/type/:profile_type' => "profiles#index", as: "profiles_by_type"
  get 'profile/new/:profile_type' => "profiles#new", as: "new_profile_by_type"

  get 'profile/full_names', to: 'profiles#full_names'
  

  root 'portal#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :profile
  validates :note, presence: {message: "Note must not be blank."}
  
  has_paper_trail :meta => { :profile_id => :prof, :description => :display}

  def prof
    self.profile_id
  end

  def display
    "Note - #{self.note.truncate(25)}"
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new(profile_id: params[:profile_id])
  end

  # GET /notes/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @profile = @note.try :profile
    
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
        format.js { render action: 'reload' }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
        format.js 
      end
    end
  end

  def reload
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
        format.js { render action: 'reload', notice: 'Note was successfully updated.' }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
      @profile = @note.try :profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:profile_id, :note)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<div id="note_form_container">
<%=javascript_tag do %>
$(document).ready(function(){
  init_note_form_container();
});
<% end %>

<%= simple_form_for @note, html: {id: 'new_note_form', class: 'span-14', remote: params[:remote]} do | f | %>

  <h3 class="titleize">
  Note For...
  </h3>

   <%= hidden_field_tag :source, params[:source]  %>
   <%= f.hidden_field :profile_id %>

   <fieldset>
   <legend><%=@note.profile.full_name%></legend>
    <%= f.input :note, label: false, input_html: {:autofocus => true}%>
    <%= f.button :submit, 'Save', data: {disable_with: "Saving...."} %>
  </fieldset>

<% end %>

app/views/notes/_note.html.erb
<tr id="note_<%=note.id%>" class="profile_note">
	<td class="note_text text">
		<%= simple_format note.note%>
	</td>
  <td class="w-8">
  <%=User.find_by_id(Note.last.originator).try :username%>
  </td>
  <td class="w-datetime">
  <%=note.updated_at.to_s(:time)%>
  </td>

  <td class="w-2">
  <%=link_to edit_img, edit_note_path(note, source: 'show', remote: true), class: 'add_overlay', remote: true %>
  </td>
  <td class="w-2">
  <%=link_to delete_img, note, remote: true, method: :delete, class: "remove_fields no-print", data: {confirm: "Delete Note?"} %>
  </td>

</tr>

app/views/notes/_table.html.erb
<table id="notes_list">
  <tbody>
    <th>Note</th>
    <th>Added By</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tbody>

  <%notes.each do | note | %>
    <%=render note%>
  <% end %>
</table>

app/views/notes/destroy.js.erb
$('#note_<%=@note.id%>').fadeOut('fast', function(){
        $(this).remove();
});

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Note</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.profile %></td>
        <td><%= note.note %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/reload.js.erb
modal_form_close();
<% if params[:source] == 'show' %>
  $('#notes_list').remove();
  $('#note_details').append('<%=j render(partial: 'notes/table', 
    locals: {notes: @profile.notes, remote: true})%>');
  $('#note_<%=@note.id%>').addClass('new');
  adjustHeight();

  $('#notes_list .add_overlay').on('click', function() {
    overlay();
  });

<% end %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @note.profile %>
</p>

<p>
  <strong>Note:</strong>
  <%= @note.note %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>