config/routes.rb
TACRM::Application.routes.draw do
  
  get "transactions/new"
  get "transactions/create"
  get "portal/index"
  get "system_updates/index"
  get "users/index"
  get "users/new"
  get "users/create"
  get "users/edit"
  get "users/update"
  get "users/show"
  get "users/destroy"
  resources :profile_versions

  devise_for :users
  scope "/admin" do
    resources :users do
      get :activate, on: :member
    end
  end

  resources :transactions

  
  resources :identifications
  get 'identification/:id/doc_image/download/:version' => 'doc_image#download', as: 'download_doc_image'
  get 'identification/:id/doc_image/new' => 'doc_image#new', as: 'new_doc_image'
  get 'identification/:id/doc_image/view' => 'doc_image#view', as: 'view_doc_image'
  post 'identification/:id/doc_image/upload' => 'doc_image#upload', as: 'upload_doc_image'
  delete 'identification/:id/doc_image/destroy' => 'doc_image#destroy', as: 'delete_doc_image'
  resources :notes

  resources :members

  resources :groups

  resources :accounts

  resources :addresses

  resources :phones

  resources :profiles do
    get  :json, on: :collection
    post :json, on: :collection
    get :datatable, on: :collection
    get :corporate_index, on: :collection
    get :lock, on: :member
    get :unlock, on: :member
    delete :delete, on: :member
    post :restore, on: :member
    get :lock_all, on: :collection
    get :unlock_all, on: :collection
    get :view_deleted, on: :collection
  end
  get 'transaction/new/profile/:profile_id' => 'transactions#new', as: 'profile_new_transaction'
  get 'identifications/passports/expiring' => 'identifications#expiring', as: 'expiring_passports'
  get 'identifications/new/profile/:profile_id' => 'identifications#new', as: 'profile_new_identification'
  get 'profile/:id/panel/:panel_number' => 'profiles#show', as: 'profile_panel'
  get 'versions/profile/:profile_id' => 'profile_versions#index', as: 'versions_profile'
  get 'profile/search' => "profiles#search", as: "profile_search"
  get 'profile/type/:profile_type' => "profiles#index", as: "profiles_by_type"
  get 'profile/new/:profile_type' => "profiles#new", as: "new_profile_by_type"

  get 'profile/full_names', to: 'profiles#full_names'
  

  root 'portal#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_one :profile, through: :account
  belongs_to :account
  has_many :members, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :account_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, remote: true) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Group Name' %><br>
    <%= f.text_field :name, class: 'focus_on_toggle' %>
    <%= f.submit %>
    <%= link_to 'Hide', '', id: "hide_group_form_link"%>
  </div>
    <%= f.hidden_field :account_id %>
<% end %>

app/views/groups/_group.html.erb
	<div id="group_<%=group.id%>" class="profile_group">
		<strong>Name: </strong><span><%=best_in_place group, :name%></span>
		<ul id="member_ul">
			<%group.members.each do | member | %>
				<%=render member%>
			<% end %>
		</ul>
		<% if can? :create, Member %>
		<div class="toggler">
		<%=link_to 'Add Member', '', id: "add_member_link_group_#{group.id}", class: 'member_link_group add_fields no-print'%>

			<% @member = Member.new(group: group)%>
			<%=render 'members/form'%>
		</div>
		<% end %>
		<%=link_to 'Delete Group', group, remote: true, method: :delete, class: "remove_fields no-print delete_group", data: {confirm: "Delete '#{group.name}'?"} %>

	</div>

app/views/groups/create.js.erb
$('#group_details').remove_loading_image();
$('#groups_list').append("<%=j render @group%>").toggle().fadeIn("fast", adjustHeight);
$('#group_<%=@group.id%> a').on('click', toggle_form);

//This causes problem with slider panel position. It makes the panel
//position to be raised upwards.
//$('#add_member_link_group_<%=@group.id%>').trigger('click');

app/views/groups/destroy.js.erb
$('#group_<%=@group.id%>').fadeOut('slow', function(){
        $(this).remove();
});

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Account</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.account %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Account:</strong>
  <%= @group.account %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>