config/routes.rb
TACRM::Application.routes.draw do
  
  get "transactions/new"
  get "transactions/create"
  get "portal/index"
  get "system_updates/index"
  get "users/index"
  get "users/new"
  get "users/create"
  get "users/edit"
  get "users/update"
  get "users/show"
  get "users/destroy"
  resources :profile_versions

  devise_for :users
  scope "/admin" do
    resources :users do
      get :activate, on: :member
    end
  end

  resources :transactions

  
  resources :identifications
  get 'identification/:id/doc_image/download/:version' => 'doc_image#download', as: 'download_doc_image'
  get 'identification/:id/doc_image/new' => 'doc_image#new', as: 'new_doc_image'
  get 'identification/:id/doc_image/view' => 'doc_image#view', as: 'view_doc_image'
  post 'identification/:id/doc_image/upload' => 'doc_image#upload', as: 'upload_doc_image'
  delete 'identification/:id/doc_image/destroy' => 'doc_image#destroy', as: 'delete_doc_image'
  resources :notes

  resources :members

  resources :groups

  resources :accounts

  resources :addresses

  resources :phones

  resources :profiles do
    get  :json, on: :collection
    post :json, on: :collection
    get :datatable, on: :collection
    get :corporate_index, on: :collection
    get :lock, on: :member
    get :unlock, on: :member
    delete :delete, on: :member
    post :restore, on: :member
    get :lock_all, on: :collection
    get :unlock_all, on: :collection
    get :view_deleted, on: :collection
  end
  get 'transaction/new/profile/:profile_id' => 'transactions#new', as: 'profile_new_transaction'
  get 'identifications/passports/expiring' => 'identifications#expiring', as: 'expiring_passports'
  get 'identifications/new/profile/:profile_id' => 'identifications#new', as: 'profile_new_identification'
  get 'profile/:id/panel/:panel_number' => 'profiles#show', as: 'profile_panel'
  get 'versions/profile/:profile_id' => 'profile_versions#index', as: 'versions_profile'
  get 'profile/search' => "profiles#search", as: "profile_search"
  get 'profile/type/:profile_type' => "profiles#index", as: "profiles_by_type"
  get 'profile/new/:profile_type' => "profiles#new", as: "new_profile_by_type"

  get 'profile/full_names', to: 'profiles#full_names'
  

  root 'portal#index'

end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  def index
    @expiring_passports = Identification.passports.where("expiration_date < ?", Date.today.to_date + 210)

  end
end

app/helpers/portal_helper.rb
module PortalHelper
end

app/views/portal/index.html.erb
<div class="portal">

<div class="controls container titleize">
  <div  class="box span-11 portal-1">
  <h3>View Client Profiles</h3>
    <ul>
      <li><%= link_to 'Individual', profiles_path(profile_type: 'Individual') %></li>
      <li><%= link_to 'Corporate', profiles_path(profile_type: 'Corporate') %></li>
    </ul>

    <h3>Internal Profiles</h3>
      <ul>
        <li><%= link_to 'Agents', profiles_path(profile_type: 'Agent') %></li>
        <li><%= link_to 'Vendor', profiles_path(profile_type: 'Vendor') %></li>
      </ul>

    <h3>Special Filters</h3>
    For Profiles with....
    <ul>
      <li><%= link_to 'No Contact Details', profiles_path(profile_type: 'NO_CONACT_DETAILS') %></li>
      <li><%= link_to 'No Address', profiles_path(profile_type: 'NO_ADDRESS') %></li>
    </ul>
  </div>

  <% if can? :create, Profile %>
  <div  class="portal-2 box span-12">
  <h3>Add New Profiles</h3>
          <ul>
          <li><%=add_profile_link titleize: true, class: '', profile_type: :individual%></li>
          <li><%=add_profile_link titleize: true, class: '', profile_type: :corporate%></li>
          <li><%=add_profile_link titleize: true, class: '', profile_type: :agent %></li>
          <li><%=add_profile_link titleize: true, class: '', profile_type: :vendor %></li>
          </ul>
  </div>
  <% end %>

  <% if current_user.try :admin? %>
  <div  class="box span-12 portal-3">
  <h3>Administration</h3>    
        <ul>
          <li><%= link_to 'User Activity', profile_versions_path %></li>
          <li><%= link_to 'Manage Users', users_path %></li>
          <li><%= link_to 'Restore Deleted Profiles', view_deleted_profiles_path%></li>
          <li><%= link_to 'View System Updates', system_updates_index_path%></li>
        </ul>
  </div>
  <% end %>
</div>

  <div  class="portal-2 box span-12">
  <h3>Transactions</h3>
          <ul>
          <li><%=link_to 'New Transaction', new_transaction_path, remote: true%></li>
          </ul>
  </div>



<hr/>
<div class="notifications">
  <div  class="box span-24">
  <h3 class="titleize">Notifications</h3> 
  <%if @expiring_passports && @expiring_passports.count > 0%>
    <%=link_to "There are #{@expiring_passports.count} Passports that are within 7 months of expiry", expiring_passports_path%>
  <% else %>
    <div> 
      <h4>-none-</h4>
    </div>
  <% end %>
  </div>

</div>

</div>