config/routes.rb
TACRM::Application.routes.draw do
  
  get "transactions/new"
  get "transactions/create"
  get "portal/index"
  get "system_updates/index"
  get "users/index"
  get "users/new"
  get "users/create"
  get "users/edit"
  get "users/update"
  get "users/show"
  get "users/destroy"
  resources :profile_versions

  devise_for :users
  scope "/admin" do
    resources :users do
      get :activate, on: :member
    end
  end

  resources :transactions

  
  resources :identifications
  get 'identification/:id/doc_image/download/:version' => 'doc_image#download', as: 'download_doc_image'
  get 'identification/:id/doc_image/new' => 'doc_image#new', as: 'new_doc_image'
  get 'identification/:id/doc_image/view' => 'doc_image#view', as: 'view_doc_image'
  post 'identification/:id/doc_image/upload' => 'doc_image#upload', as: 'upload_doc_image'
  delete 'identification/:id/doc_image/destroy' => 'doc_image#destroy', as: 'delete_doc_image'
  resources :notes

  resources :members

  resources :groups

  resources :accounts

  resources :addresses

  resources :phones

  resources :profiles do
    get  :json, on: :collection
    post :json, on: :collection
    get :datatable, on: :collection
    get :corporate_index, on: :collection
    get :lock, on: :member
    get :unlock, on: :member
    delete :delete, on: :member
    post :restore, on: :member
    get :lock_all, on: :collection
    get :unlock_all, on: :collection
    get :view_deleted, on: :collection
  end
  get 'transaction/new/profile/:profile_id' => 'transactions#new', as: 'profile_new_transaction'
  get 'identifications/passports/expiring' => 'identifications#expiring', as: 'expiring_passports'
  get 'identifications/new/profile/:profile_id' => 'identifications#new', as: 'profile_new_identification'
  get 'profile/:id/panel/:panel_number' => 'profiles#show', as: 'profile_panel'
  get 'versions/profile/:profile_id' => 'profile_versions#index', as: 'versions_profile'
  get 'profile/search' => "profiles#search", as: "profile_search"
  get 'profile/type/:profile_type' => "profiles#index", as: "profiles_by_type"
  get 'profile/new/:profile_type' => "profiles#new", as: "new_profile_by_type"

  get 'profile/full_names', to: 'profiles#full_names'
  

  root 'portal#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :profile
  has_many :groups, dependent: :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    puts "Current USer: #{current_user}"
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account.profile, notice: 'Account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      puts "Current USer: #{current_user}"
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :profile_id)
    end

    def auth_params
      @user = User.new(user_params)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
  <%= form_tag(profile_search_path, method: 'get', remote: true ) do %>
      <%= label_tag(:term, "Profile Name:")%>
      <%= text_field_tag(:term)%>
      <%= submit_tag("Search")%>
  <% end %>

  <div id="xxxx">
    <h1>Profiles</h1>
  </div>

<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.text_field :profile_id %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_form2.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Account Name' %> <%= f.text_field :name, class: 'focus_on_toggle' %>
    <%= f.submit %> 
    <%= link_to 'Hide', '', id: "hide_create_account_form_link" %>
  </div>
    <%= f.hidden_field :profile_id %>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div id="section_title">
All Clients
</div>
<div id="section_controls">
<%=link_to 'Add Corporate', '', class: 'add_fields'%>
<%=link_to 'Add Individual', '', class: 'add_fields'%> 
</div>
<div id="section_content">
<table class="section_table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Type</th>
      <th>Email</th>
      <th>Contact Number</th>
      <th>Address</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr class="<%=cycle('odd','even')%>">
        <td class="view">
          <div>
          <%= link_to 'View Details', account.profile, class: 'std_button' %>
          </div>
        </td>
        <td><%= account.name %></td>
        <td><%= account.profile.profile_type %></td>
        <td><%= account.profile.email if account.profile %></td>
        <td><%= account.profile.phones.first.try :display %></td>
        <td><%= truncate account.profile.addresses.first.try(:display) %></td>
        <td><%= link_to 'X', account, method: :delete, class: "remove_fields", data: { confirm: "Delete Account '#{account.name}'?" } %>
    </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="table_botom_spacer">&nbsp</div>

</div>

<!--%= link_to 'New Account', new_account_path %-->

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @account.profile %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>